//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actas()
        {
            this.DetalleActa = new HashSet<DetalleActa>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdTipoActa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual TipoActa TipoActa { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleActa> DetalleActa { get; set; }
    }
}
