//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcuerdoPagoCuentasPendientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcuerdoPagoCuentasPendientes()
        {
            this.CuotasPagoPendiente = new HashSet<CuotasPagoPendiente>();
        }
    
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public int IdUsuario { get; set; }
        public int NroCuotas { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string FormaPago { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> DiasPago { get; set; }
    
        public virtual CuentasPendientes CuentasPendientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuotasPagoPendiente> CuotasPagoPendiente { get; set; }
    }
}
