//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brief
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brief()
        {
            this.FotosBrief = new HashSet<FotosBrief>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosBrief> FotosBrief { get; set; }
    }
}
