//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasPendientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasPendientes()
        {
            this.AcuerdoPagoCuentasPendientes = new HashSet<AcuerdoPagoCuentasPendientes>();
        }
    
        public int Id { get; set; }
        public string NumeroCotizacion { get; set; }
        public int IdCliente { get; set; }
        public decimal SaldoTotal { get; set; }
        public string DescripcionFactura { get; set; }
        public int IdUsuario { get; set; }
        public string EstadoPago { get; set; }
        public decimal SaldoPendiente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdoPagoCuentasPendientes> AcuerdoPagoCuentasPendientes { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
