//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotasPagoPendiente
    {
        public int Id { get; set; }
        public int IdAcuerdo { get; set; }
        public decimal Valor { get; set; }
        public string Fecha { get; set; }
        public string Estado { get; set; }
        public int NroCuota { get; set; }
        public Nullable<int> Usuario { get; set; }
        public decimal SaldoCapital { get; set; }
        public decimal SaldoPendiente { get; set; }
        public Nullable<int> IdModoPago { get; set; }
    
        public virtual AcuerdoPagoCuentasPendientes AcuerdoPagoCuentasPendientes { get; set; }
        public virtual ModoPago ModoPago { get; set; }
    }
}
