//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaPago
    {
        public int Id { get; set; }
        public int IdPlanPago { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Fecha { get; set; }
        public string Estado { get; set; }
        public string UsuarioRecibePago { get; set; }
        public decimal ValorPagado { get; set; }
        public decimal SaldoCapital { get; set; }
        public decimal SaldoPendiente { get; set; }
        public int NroCuota { get; set; }
    
        public virtual PlanPagoCredito PlanPagoCredito { get; set; }
    }
}
