//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRemisiones
    {
        public int ID { get; set; }
        public Nullable<int> IdRemision { get; set; }
        public Nullable<int> IdItem { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual RemisionesExternas RemisionesExternas { get; set; }
    }
}
