//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentos()
        {
            this.Actas = new HashSet<Actas>();
            this.ControlEntregasInternas = new HashSet<ControlEntregasInternas>();
            this.Modificaciones = new HashSet<Modificaciones>();
            this.PlanPagoCredito = new HashSet<PlanPagoCredito>();
            this.Procesos = new HashSet<Procesos>();
            this.ProgramacionTarea = new HashSet<ProgramacionTarea>();
            this.RemisionesExternas = new HashSet<RemisionesExternas>();
        }
    
        public int ID { get; set; }
        public int Id_empresa { get; set; }
        public int Id_Bodega { get; set; }
        public int IdTipoMovimiento { get; set; }
        public Nullable<int> DiasValidez { get; set; }
        public decimal TotalSub { get; set; }
        public decimal Total_Descuento { get; set; }
        public decimal Total { get; set; }
        public string NotasInternas { get; set; }
        public string Notas { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdDocumentoAnterior { get; set; }
        public int EstadoDocumento { get; set; }
        public int IdFormaPago { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public decimal TotalIva { get; set; }
        public string EstadoPago { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public int NumeroCotizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actas> Actas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlEntregasInternas> ControlEntregasInternas { get; set; }
        public virtual EstadoDocumento EstadoDocumento1 { get; set; }
        public virtual FomaDePago FomaDePago { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modificaciones> Modificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanPagoCredito> PlanPagoCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesos> Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramacionTarea> ProgramacionTarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemisionesExternas> RemisionesExternas { get; set; }
    }
}
