//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int ID { get; set; }
        public int IdItem { get; set; }
        public Nullable<int> CantidadAnterior { get; set; }
        public Nullable<int> CantidadDespachada { get; set; }
        public int CantidadDisponible { get; set; }
        public int IdBodega { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
