//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.DetalleDocumento = new HashSet<DetalleDocumento>();
            this.DetalleRemisiones = new HashSet<DetalleRemisiones>();
            this.FotosItems = new HashSet<FotosItems>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int ID { get; set; }
        public int IdEmpresa { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Subgrupo { get; set; }
        public int IdIva { get; set; }
        public int MaxDescuento { get; set; }
        public Nullable<int> CantidadMinima { get; set; }
        public Nullable<int> CantidadMaxima { get; set; }
        public int Anulado { get; set; }
        public int NumeroDecimales { get; set; }
        public string Notas { get; set; }
        public int IdColor { get; set; }
        public string Modelo { get; set; }
        public string NroSerie { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string FechaVencimiento { get; set; }
        public bool ManejaStock { get; set; }
        public int IdTalla { get; set; }
        public Nullable<int> StockActual { get; set; }
        public Nullable<int> DiasReposicion { get; set; }
        public string CalificacionABC { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public bool Estado { get; set; }
        public decimal PrecioCompra { get; set; }
        public int CantidadExistente { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> ComisionPorVenta { get; set; }
        public string ReferenciaProveedor { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDocumento> DetalleDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRemisiones> DetalleRemisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosItems> FotosItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Iva Iva { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual SubGrupo SubGrupo1 { get; set; }
        public virtual Talla Talla { get; set; }
        public virtual Users Users { get; set; }
    }
}
