//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.CuentasPendientes = new HashSet<CuentasPendientes>();
            this.Documentos = new HashSet<Documentos>();
            this.Nomina = new HashSet<Nomina>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public int CiudadResidencia { get; set; }
        public string Nota { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> TipoPersona { get; set; }
        public Nullable<bool> RegimenSimplificado { get; set; }
        public int IdEmpesa { get; set; }
        public Nullable<bool> Autoretenedores { get; set; }
        public Nullable<bool> AplicaAIU { get; set; }
        public string Contacto { get; set; }
        public Nullable<bool> RecibirEmail { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> DiasCreditoProve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasPendientes> CuentasPendientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nomina { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
        public virtual TipoPersona TipoPersona1 { get; set; }
    }
}
