//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPagoCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanPagoCredito()
        {
            this.CuotaPago = new HashSet<CuotaPago>();
        }
    
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public Nullable<System.DateTime> FechaAcuerdo { get; set; }
        public Nullable<int> NroCuotas { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string ModoPago { get; set; }
        public Nullable<int> DiasPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuotaPago> CuotaPago { get; set; }
        public virtual Documentos Documentos { get; set; }
    }
}
