//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionTarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramacionTarea()
        {
            this.ControlDeProcesos = new HashSet<ControlDeProcesos>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdProceso { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlDeProcesos> ControlDeProcesos { get; set; }
        public virtual Documentos Documentos { get; set; }
        public virtual Procesos Procesos { get; set; }
        public virtual Users Users { get; set; }
    }
}
