//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBrakGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosPago
    {
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public int IdAcuerdo { get; set; }
        public int NroCuota { get; set; }
        public decimal ValorRecibido { get; set; }
        public decimal ValorDevuelto { get; set; }
        public decimal ValorTotal { get; set; }
        public string ModoPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Anulado { get; set; }
        public string Notas { get; set; }
        public string Usuario { get; set; }
    }
}
